#!/usr/bin/env ruby

require 'json'

# depends on heroku-builds plugin

def run(command)
  puts command
  `#{command}`.tap &method(:puts)
end

def load_json(file_name)
  JSON.parse File.read(file_name)
end

def write_json(file_name, hash)
  puts "Writing #{file_name}"
  File.write(file_name, JSON.dump(hash))
end

def move_local_dependencies_into_subdirectory
  package_json = load_json './package.json'
  dependency_overrides = load_json './deployment/dependency_overrides.json'
  package_json['dependencies'].merge! dependency_overrides
  write_json './package.json', package_json
end

root_dir = run('git rev-parse --show-toplevel').strip
server_dir = "#{root_dir}/server"
deploy_dir = "#{root_dir}/deploy"
run "rsync -av --exclude='.git' --exclude-from='#{server_dir}/.gitignore' #{server_dir}/ #{deploy_dir}"

Dir.chdir(deploy_dir) do
  puts "cd #{deploy_dir}"
  move_local_dependencies_into_subdirectory
  run 'heroku builds:create -a hands-free-recipe'
  puts 'cd -'
end

run "rm -rf #{deploy_dir}"


