#!/usr/bin/env ruby

require 'json'

# depends on heroku-builds plugin

def run(command)
  puts command
  `#{command}`.tap &method(:puts)
end

def load_json(file_name)
  JSON.parse File.read(file_name)
end
def replace_in_file(file_name, to_replace, substitution)
  content = File.read(file_name)
  File.write file_name, content.gsub(to_replace, substitution)
end

def copy_repo(source, destination)
  run "rsync -av --exclude='.git' --exclude-from='#{source}/.gitignore' #{source}/ #{destination}"
end

def copy_repo_into(source, destination)
  run "rsync -av --exclude='.git' --exclude-from='#{source}/.gitignore' #{source} #{destination}"
end

def move_local_dependencies_into_subdirectory
  puts 'Changing dependency locations'
  dependency_overrides = load_json './deployment/dependency_overrides.json'
  dependency_overrides.each do |original, replacement|
    replace_in_file './package.json', original, replacement
    replace_in_file './yarn.lock', original, replacement
  end
end

root_dir = run('git rev-parse --show-toplevel').strip
server_dir = "#{root_dir}/server"
parser_dir = "#{root_dir}/recipe-parser"
deploy_dir = "#{root_dir}/deploy"
dependencies_dir = "#{deploy_dir}/dependencies"
copy_repo server_dir, deploy_dir
`mkdir #{dependencies_dir}`
copy_repo_into parser_dir, dependencies_dir

Dir.chdir(deploy_dir) do
  puts "cd #{deploy_dir}"
  move_local_dependencies_into_subdirectory
  run 'heroku builds:create -a hands-free-recipe'
  puts 'cd -'
end

run "rm -rf #{deploy_dir}"


